language: node_js
node_js:
    - "0.12"
# before_script:
#    - npm install -g gulp
#script: gulp
script: ./travis-test.sh

notifications:
    slack:
      rooms:
        - buildo:iVeL8b7n4t8Mkif5nJmHmsix#frontends
